name: CWT Model Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-harvest numpy joblib scikit-learn
        pip install torch tensorflow transformers
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create necessary directories
      run: |
        mkdir -p logs/installation
        mkdir -p models/advanced
        mkdir -p models/deep_learning
        mkdir -p models/huggingface
    
    - name: Run utility tests
      run: |
        pytest tests/utilities/test_download_advanced_models.py -v --cov=utilities
    
    - name: Run traditional ML model tests
      run: |
        pytest tests/models/test_advanced_models.py -v --cov=models
    
    - name: Run deep learning model tests
      run: |
        pytest tests/models/test_deep_learning_models.py -v --cov=models
    
    - name: Run transformer model tests
      run: |
        pytest tests/models/test_huggingface_models.py -v --cov=models
    
    - name: Run integration tests
      run: |
        pytest tests/integration/test_model_workflow.py -v --cov=.
    
    - name: Generate coverage report
      run: |
        pytest --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true 